[project]
name = "email-tools"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "curl-cffi>=0.11.1",
    "loguru>=0.7.3",
    "python-dateutil>=2.9.0.post0",
]
